### ISSUE TITLE
`pragmatist test` failing with ES6 errors

### ISSUE THREAD

**Issue by bitspook** [gajus/pragmatist#11]
Any idea why this might be happening? If I comment out `import` statements in tests, it fails saying `let and const are only allowed in strict mode`. I've tried running tests with `node ./node_modules/.bin/pragmatist test` i.e no "--browser" but it still fails with same error. Here's the repository I am using it on: https://github.com/gajus/react-carousel

Pragmatist version is 2.3.2, and I don't have a .babelrc

``` bash
npm run test

> react-carousel@3.1.1 test /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel
> npm run pragmatist test


> react-carousel@3.1.1 pragmatist /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel
> node ./node_modules/.bin/pragmatist --browser "test"

[08:51:45] Starting 'pragmatist:task-pre-copy-clean'...
[08:51:45] Finished 'pragmatist:task-pre-copy-clean' after 44 ms
[08:51:45] Starting 'pragmatist:test-copy'...
[08:51:45] Finished 'pragmatist:test-copy' after 108 ms
[08:51:45] Starting 'pragmatist:test-build'...
[08:51:47] Finished 'pragmatist:test-build' after 1.87 s
[08:51:47] Starting 'pragmatist:test-hook-require'...
[08:51:47] Finished 'pragmatist:test-hook-require' after 7.98 ms
[08:51:47] Starting 'pragmatist:test-run'...
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at runFn (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/async/lib/async.js:52:16
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/async/lib/async.js:361:13
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/async/lib/async.js:52:16
    at done (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/async/lib/async.js:246:17)
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/async/lib/async.js:44:16
    at /Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1614:14)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
No coverage information was collected, exit without writing coverage information
[08:52:02]

name:    Error
message: Mocha exited with code 1
plugin:  gulp-spawn-mocha

[08:52:02] 'pragmatist:test-run' errored after 15 s
[08:52:02] Error in plugin 'gulp-spawn-mocha'
Mocha exited with code 1

/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/orchestrator/index.js:153
            throw err;
            ^
Error: Mocha exited with code 1
    at ChildProcess.<anonymous> (/Users/channi/Documents/Work/applaudience/showtimes-components/react-carousel/node_modules/pragmatist/node_modules/gulp-spawn-mocha/lib/index.js:58:28)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at maybeClose (internal/child_process.js:819:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
```

**Comment by bitspook** [comment]
With new changes pulled from react-carousel:master, it is working now. I have no idea what went wrong and why it's working again.
